{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "g-rump.fullname" . }}
  labels:
    {{- include "g-rump.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "g-rump.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    path: /metrics
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    scheme: http
{{- end }}
